// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/catalog_meta_entity.dart';
import 'src/puzzle_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7222435052136685866),
    name: 'CatalogMetaEntity',
    lastPropertyId: const obx_int.IdUid(16, 5361497717474733693),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 500612299266530667),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5782081772456567651),
        name: 'catalogId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6905926200269102521),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6111787636116635896),
        name: 'catalogSchemaVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6595226800071566378),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 196283396692085983),
        name: 'createdAtUtcMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7329573228846255086),
        name: 'sourceName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6370520348199662824),
        name: 'sourceFile',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5722708943802314226),
        name: 'sourceDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7619058967542184415),
        name: 'sourceSha256',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8087518685847816959),
        name: 'catalogModelFingerprint',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7613157164189558187),
        name: 'puzzleCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4103642622323047215),
        name: 'minRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6007563894127367238),
        name: 'maxRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 494779115788541989),
        name: 'ratingBucketSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 919300552959361275),
        name: 'themeDictionaryVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5361497717474733693),
        name: 'themeDictionarySha256',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4032578052764687250),
    name: 'PuzzleEntity',
    lastPropertyId: const obx_int.IdUid(20, 6602035108214826858),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4864430366868117293),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7704425131413672588),
        name: 'lichessPuzzleId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 5330921247863387048),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7495437996446923796),
        name: 'sourceFen',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8381760580012730701),
        name: 'setupMoveUci',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2296278808988348994),
        name: 'puzzleFen',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2368609292546383074),
        name: 'movesUci',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8904288275141166300),
        name: 'solutionMovesUci',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7568326827235247035),
        name: 'solutionPlyCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8615843305702429828),
        name: 'playerColor',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(3, 8082162448884677458),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5184318142129959560),
        name: 'rating',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(4, 3045460081408792418),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6023309680638471977),
        name: 'ratingBucket',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(5, 6503195156251777203),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6517666201038560634),
        name: 'ratingDeviation',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4245200120839882708),
        name: 'popularity',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(6, 7279904091618283261),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6317675728251557677),
        name: 'nbPlays',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 9089614117665705778),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8091726879409438388),
        name: 'themes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7740613688678851289),
        name: 'openingTags',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6139658544549906136),
        name: 'gameUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 795438971370621484),
        name: 'themeMaskLow',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 4310850192088128260),
        name: 'themeMaskHigh',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 6602035108214826858),
        name: 'randomKey',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(8, 4895199861874324419),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4032578052764687250),
    lastIndexId: const obx_int.IdUid(8, 4895199861874324419),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CatalogMetaEntity: obx_int.EntityDefinition<CatalogMetaEntity>(
      model: _entities[0],
      toOneRelations: (CatalogMetaEntity object) => [],
      toManyRelations: (CatalogMetaEntity object) => {},
      getId: (CatalogMetaEntity object) => object.id,
      setId: (CatalogMetaEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CatalogMetaEntity object, fb.Builder fbb) {
        final catalogIdOffset = fbb.writeString(object.catalogId);
        final displayNameOffset = fbb.writeString(object.displayName);
        final sourceNameOffset = fbb.writeString(object.sourceName);
        final sourceFileOffset = fbb.writeString(object.sourceFile);
        final sourceDateOffset = fbb.writeString(object.sourceDate);
        final sourceSha256Offset = fbb.writeString(object.sourceSha256);
        final catalogModelFingerprintOffset = fbb.writeString(
          object.catalogModelFingerprint,
        );
        final themeDictionarySha256Offset = fbb.writeString(
          object.themeDictionarySha256,
        );
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, catalogIdOffset);
        fbb.addInt64(2, object.catalogSchemaVersion);
        fbb.addOffset(3, displayNameOffset);
        fbb.addInt64(4, object.createdAtUtcMs);
        fbb.addOffset(5, sourceNameOffset);
        fbb.addOffset(6, sourceFileOffset);
        fbb.addOffset(7, sourceDateOffset);
        fbb.addOffset(8, sourceSha256Offset);
        fbb.addOffset(9, catalogModelFingerprintOffset);
        fbb.addInt64(10, object.puzzleCount);
        fbb.addInt64(11, object.minRating);
        fbb.addInt64(12, object.maxRating);
        fbb.addInt64(13, object.ratingBucketSize);
        fbb.addInt64(14, object.themeDictionaryVersion);
        fbb.addOffset(15, themeDictionarySha256Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final catalogIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final catalogSchemaVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtUtcMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final sourceNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final sourceFileParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final sourceDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final sourceSha256Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final catalogModelFingerprintParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final puzzleCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final minRatingParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final maxRatingParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final ratingBucketSizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final themeDictionaryVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final themeDictionarySha256Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final object = CatalogMetaEntity(
          id: idParam,
          catalogId: catalogIdParam,
          catalogSchemaVersion: catalogSchemaVersionParam,
          displayName: displayNameParam,
          createdAtUtcMs: createdAtUtcMsParam,
          sourceName: sourceNameParam,
          sourceFile: sourceFileParam,
          sourceDate: sourceDateParam,
          sourceSha256: sourceSha256Param,
          catalogModelFingerprint: catalogModelFingerprintParam,
          puzzleCount: puzzleCountParam,
          minRating: minRatingParam,
          maxRating: maxRatingParam,
          ratingBucketSize: ratingBucketSizeParam,
          themeDictionaryVersion: themeDictionaryVersionParam,
          themeDictionarySha256: themeDictionarySha256Param,
        );

        return object;
      },
    ),
    PuzzleEntity: obx_int.EntityDefinition<PuzzleEntity>(
      model: _entities[1],
      toOneRelations: (PuzzleEntity object) => [],
      toManyRelations: (PuzzleEntity object) => {},
      getId: (PuzzleEntity object) => object.id,
      setId: (PuzzleEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PuzzleEntity object, fb.Builder fbb) {
        final lichessPuzzleIdOffset = fbb.writeString(object.lichessPuzzleId);
        final sourceFenOffset = fbb.writeString(object.sourceFen);
        final setupMoveUciOffset = fbb.writeString(object.setupMoveUci);
        final puzzleFenOffset = fbb.writeString(object.puzzleFen);
        final movesUciOffset = fbb.writeString(object.movesUci);
        final solutionMovesUciOffset = fbb.writeString(object.solutionMovesUci);
        final themesOffset = fbb.writeString(object.themes);
        final openingTagsOffset = fbb.writeString(object.openingTags);
        final gameUrlOffset = fbb.writeString(object.gameUrl);
        fbb.startTable(21);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, lichessPuzzleIdOffset);
        fbb.addOffset(2, sourceFenOffset);
        fbb.addOffset(3, setupMoveUciOffset);
        fbb.addOffset(4, puzzleFenOffset);
        fbb.addOffset(5, movesUciOffset);
        fbb.addOffset(6, solutionMovesUciOffset);
        fbb.addInt64(7, object.solutionPlyCount);
        fbb.addInt64(8, object.playerColor);
        fbb.addInt64(9, object.rating);
        fbb.addInt64(10, object.ratingBucket);
        fbb.addInt64(11, object.ratingDeviation);
        fbb.addInt64(12, object.popularity);
        fbb.addInt64(13, object.nbPlays);
        fbb.addOffset(14, themesOffset);
        fbb.addOffset(15, openingTagsOffset);
        fbb.addOffset(16, gameUrlOffset);
        fbb.addInt64(17, object.themeMaskLow);
        fbb.addInt64(18, object.themeMaskHigh);
        fbb.addInt64(19, object.randomKey);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final lichessPuzzleIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sourceFenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final setupMoveUciParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final puzzleFenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final movesUciParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final solutionMovesUciParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final solutionPlyCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final playerColorParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final ratingParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final ratingBucketParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final ratingDeviationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final popularityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final nbPlaysParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final themesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final openingTagsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final themeMaskLowParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final themeMaskHighParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final randomKeyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final gameUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final object = PuzzleEntity(
          id: idParam,
          lichessPuzzleId: lichessPuzzleIdParam,
          sourceFen: sourceFenParam,
          setupMoveUci: setupMoveUciParam,
          puzzleFen: puzzleFenParam,
          movesUci: movesUciParam,
          solutionMovesUci: solutionMovesUciParam,
          solutionPlyCount: solutionPlyCountParam,
          playerColor: playerColorParam,
          rating: ratingParam,
          ratingBucket: ratingBucketParam,
          ratingDeviation: ratingDeviationParam,
          popularity: popularityParam,
          nbPlays: nbPlaysParam,
          themes: themesParam,
          openingTags: openingTagsParam,
          themeMaskLow: themeMaskLowParam,
          themeMaskHigh: themeMaskHighParam,
          randomKey: randomKeyParam,
          gameUrl: gameUrlParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CatalogMetaEntity] entity fields to define ObjectBox queries.
class CatalogMetaEntity_ {
  /// See [CatalogMetaEntity.id].
  static final id = obx.QueryIntegerProperty<CatalogMetaEntity>(
    _entities[0].properties[0],
  );

  /// See [CatalogMetaEntity.catalogId].
  static final catalogId = obx.QueryStringProperty<CatalogMetaEntity>(
    _entities[0].properties[1],
  );

  /// See [CatalogMetaEntity.catalogSchemaVersion].
  static final catalogSchemaVersion =
      obx.QueryIntegerProperty<CatalogMetaEntity>(_entities[0].properties[2]);

  /// See [CatalogMetaEntity.displayName].
  static final displayName = obx.QueryStringProperty<CatalogMetaEntity>(
    _entities[0].properties[3],
  );

  /// See [CatalogMetaEntity.createdAtUtcMs].
  static final createdAtUtcMs = obx.QueryIntegerProperty<CatalogMetaEntity>(
    _entities[0].properties[4],
  );

  /// See [CatalogMetaEntity.sourceName].
  static final sourceName = obx.QueryStringProperty<CatalogMetaEntity>(
    _entities[0].properties[5],
  );

  /// See [CatalogMetaEntity.sourceFile].
  static final sourceFile = obx.QueryStringProperty<CatalogMetaEntity>(
    _entities[0].properties[6],
  );

  /// See [CatalogMetaEntity.sourceDate].
  static final sourceDate = obx.QueryStringProperty<CatalogMetaEntity>(
    _entities[0].properties[7],
  );

  /// See [CatalogMetaEntity.sourceSha256].
  static final sourceSha256 = obx.QueryStringProperty<CatalogMetaEntity>(
    _entities[0].properties[8],
  );

  /// See [CatalogMetaEntity.catalogModelFingerprint].
  static final catalogModelFingerprint =
      obx.QueryStringProperty<CatalogMetaEntity>(_entities[0].properties[9]);

  /// See [CatalogMetaEntity.puzzleCount].
  static final puzzleCount = obx.QueryIntegerProperty<CatalogMetaEntity>(
    _entities[0].properties[10],
  );

  /// See [CatalogMetaEntity.minRating].
  static final minRating = obx.QueryIntegerProperty<CatalogMetaEntity>(
    _entities[0].properties[11],
  );

  /// See [CatalogMetaEntity.maxRating].
  static final maxRating = obx.QueryIntegerProperty<CatalogMetaEntity>(
    _entities[0].properties[12],
  );

  /// See [CatalogMetaEntity.ratingBucketSize].
  static final ratingBucketSize = obx.QueryIntegerProperty<CatalogMetaEntity>(
    _entities[0].properties[13],
  );

  /// See [CatalogMetaEntity.themeDictionaryVersion].
  static final themeDictionaryVersion =
      obx.QueryIntegerProperty<CatalogMetaEntity>(_entities[0].properties[14]);

  /// See [CatalogMetaEntity.themeDictionarySha256].
  static final themeDictionarySha256 =
      obx.QueryStringProperty<CatalogMetaEntity>(_entities[0].properties[15]);
}

/// [PuzzleEntity] entity fields to define ObjectBox queries.
class PuzzleEntity_ {
  /// See [PuzzleEntity.id].
  static final id = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[0],
  );

  /// See [PuzzleEntity.lichessPuzzleId].
  static final lichessPuzzleId = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[1],
  );

  /// See [PuzzleEntity.sourceFen].
  static final sourceFen = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[2],
  );

  /// See [PuzzleEntity.setupMoveUci].
  static final setupMoveUci = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[3],
  );

  /// See [PuzzleEntity.puzzleFen].
  static final puzzleFen = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[4],
  );

  /// See [PuzzleEntity.movesUci].
  static final movesUci = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[5],
  );

  /// See [PuzzleEntity.solutionMovesUci].
  static final solutionMovesUci = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[6],
  );

  /// See [PuzzleEntity.solutionPlyCount].
  static final solutionPlyCount = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[7],
  );

  /// See [PuzzleEntity.playerColor].
  static final playerColor = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[8],
  );

  /// See [PuzzleEntity.rating].
  static final rating = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[9],
  );

  /// See [PuzzleEntity.ratingBucket].
  static final ratingBucket = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[10],
  );

  /// See [PuzzleEntity.ratingDeviation].
  static final ratingDeviation = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[11],
  );

  /// See [PuzzleEntity.popularity].
  static final popularity = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[12],
  );

  /// See [PuzzleEntity.nbPlays].
  static final nbPlays = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[13],
  );

  /// See [PuzzleEntity.themes].
  static final themes = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[14],
  );

  /// See [PuzzleEntity.openingTags].
  static final openingTags = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[15],
  );

  /// See [PuzzleEntity.gameUrl].
  static final gameUrl = obx.QueryStringProperty<PuzzleEntity>(
    _entities[1].properties[16],
  );

  /// See [PuzzleEntity.themeMaskLow].
  static final themeMaskLow = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[17],
  );

  /// See [PuzzleEntity.themeMaskHigh].
  static final themeMaskHigh = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[18],
  );

  /// See [PuzzleEntity.randomKey].
  static final randomKey = obx.QueryIntegerProperty<PuzzleEntity>(
    _entities[1].properties[19],
  );
}
