// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/puzzle_progress_entity.dart';
import 'src/puzzle_run_entity.dart';
import 'src/puzzle_settings_entity.dart';
import 'src/user_store_meta_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8862000106999246205),
    name: 'PuzzleProgressEntity',
    lastPropertyId: const obx_int.IdUid(10, 6816352674654132996),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7509318718690922479),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6902477662408331290),
        name: 'lichessPuzzleId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 7503662630407456022),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2034898239114396499),
        name: 'solved',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3114505515841471613),
        name: 'failed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1273297180470417698),
        name: 'attempts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 152024860634825688),
        name: 'solvedCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 297809739003150128),
        name: 'failedCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5377939063642702752),
        name: 'bestTimeMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7502464100021774336),
        name: 'firstSolvedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6816352674654132996),
        name: 'lastPlayedAtMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 623527614888720126),
    name: 'PuzzleRunEntity',
    lastPropertyId: const obx_int.IdUid(11, 149959583633955938),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2137514930380325738),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1067164091697929809),
        name: 'catalogId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4144192260262780232),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5052379170720645982),
        name: 'mode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7740477589593426677),
        name: 'startedAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(3, 5537391396795520352),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5422719788406901511),
        name: 'endedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7563980215125010059),
        name: 'score',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6288812803715029686),
        name: 'streak',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3450391133728551473),
        name: 'mistakes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2584725949768862474),
        name: 'minRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6560044463459980990),
        name: 'maxRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 149959583633955938),
        name: 'randomMode',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1880154504866592291),
    name: 'PuzzleSettingsEntity',
    lastPropertyId: const obx_int.IdUid(5, 3968459840073216401),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6899116114219243456),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5928782739152641707),
        name: 'minRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3111244006932469180),
        name: 'maxRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6880285838764420196),
        name: 'randomMode',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3968459840073216401),
        name: 'selectedMode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6471625215311251562),
    name: 'UserStoreMetaEntity',
    lastPropertyId: const obx_int.IdUid(4, 2412049437298893951),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5553487793611467981),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 36705763151100660),
        name: 'schemaVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4668062693663043145),
        name: 'createdAtUtcMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2412049437298893951),
        name: 'lastOpenedAtUtcMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 6471625215311251562),
    lastIndexId: const obx_int.IdUid(3, 5537391396795520352),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PuzzleProgressEntity: obx_int.EntityDefinition<PuzzleProgressEntity>(
      model: _entities[0],
      toOneRelations: (PuzzleProgressEntity object) => [],
      toManyRelations: (PuzzleProgressEntity object) => {},
      getId: (PuzzleProgressEntity object) => object.id,
      setId: (PuzzleProgressEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PuzzleProgressEntity object, fb.Builder fbb) {
        final lichessPuzzleIdOffset = fbb.writeString(object.lichessPuzzleId);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, lichessPuzzleIdOffset);
        fbb.addBool(2, object.solved);
        fbb.addBool(3, object.failed);
        fbb.addInt64(4, object.attempts);
        fbb.addInt64(5, object.solvedCount);
        fbb.addInt64(6, object.failedCount);
        fbb.addInt64(7, object.bestTimeMs);
        fbb.addInt64(8, object.firstSolvedAtMs);
        fbb.addInt64(9, object.lastPlayedAtMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final lichessPuzzleIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final solvedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final failedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final attemptsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final solvedCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final failedCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final bestTimeMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final firstSolvedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final lastPlayedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final object = PuzzleProgressEntity(
          id: idParam,
          lichessPuzzleId: lichessPuzzleIdParam,
          solved: solvedParam,
          failed: failedParam,
          attempts: attemptsParam,
          solvedCount: solvedCountParam,
          failedCount: failedCountParam,
          bestTimeMs: bestTimeMsParam,
          firstSolvedAtMs: firstSolvedAtMsParam,
          lastPlayedAtMs: lastPlayedAtMsParam,
        );

        return object;
      },
    ),
    PuzzleRunEntity: obx_int.EntityDefinition<PuzzleRunEntity>(
      model: _entities[1],
      toOneRelations: (PuzzleRunEntity object) => [],
      toManyRelations: (PuzzleRunEntity object) => {},
      getId: (PuzzleRunEntity object) => object.id,
      setId: (PuzzleRunEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PuzzleRunEntity object, fb.Builder fbb) {
        final catalogIdOffset = fbb.writeString(object.catalogId);
        final modeOffset = fbb.writeString(object.mode);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, catalogIdOffset);
        fbb.addOffset(2, modeOffset);
        fbb.addInt64(3, object.startedAtMs);
        fbb.addInt64(4, object.endedAtMs);
        fbb.addInt64(5, object.score);
        fbb.addInt64(6, object.streak);
        fbb.addInt64(7, object.mistakes);
        fbb.addInt64(8, object.minRating);
        fbb.addInt64(9, object.maxRating);
        fbb.addBool(10, object.randomMode);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final catalogIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final modeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final endedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final scoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final streakParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final mistakesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final minRatingParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final maxRatingParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final randomModeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final object = PuzzleRunEntity(
          id: idParam,
          catalogId: catalogIdParam,
          mode: modeParam,
          startedAtMs: startedAtMsParam,
          endedAtMs: endedAtMsParam,
          score: scoreParam,
          streak: streakParam,
          mistakes: mistakesParam,
          minRating: minRatingParam,
          maxRating: maxRatingParam,
          randomMode: randomModeParam,
        );

        return object;
      },
    ),
    PuzzleSettingsEntity: obx_int.EntityDefinition<PuzzleSettingsEntity>(
      model: _entities[2],
      toOneRelations: (PuzzleSettingsEntity object) => [],
      toManyRelations: (PuzzleSettingsEntity object) => {},
      getId: (PuzzleSettingsEntity object) => object.id,
      setId: (PuzzleSettingsEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PuzzleSettingsEntity object, fb.Builder fbb) {
        final selectedModeOffset = fbb.writeString(object.selectedMode);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.minRating);
        fbb.addInt64(2, object.maxRating);
        fbb.addBool(3, object.randomMode);
        fbb.addOffset(4, selectedModeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final minRatingParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final maxRatingParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final randomModeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final selectedModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = PuzzleSettingsEntity(
          id: idParam,
          minRating: minRatingParam,
          maxRating: maxRatingParam,
          randomMode: randomModeParam,
          selectedMode: selectedModeParam,
        );

        return object;
      },
    ),
    UserStoreMetaEntity: obx_int.EntityDefinition<UserStoreMetaEntity>(
      model: _entities[3],
      toOneRelations: (UserStoreMetaEntity object) => [],
      toManyRelations: (UserStoreMetaEntity object) => {},
      getId: (UserStoreMetaEntity object) => object.id,
      setId: (UserStoreMetaEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserStoreMetaEntity object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.schemaVersion);
        fbb.addInt64(2, object.createdAtUtcMs);
        fbb.addInt64(3, object.lastOpenedAtUtcMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final schemaVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final createdAtUtcMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final lastOpenedAtUtcMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = UserStoreMetaEntity(
          id: idParam,
          schemaVersion: schemaVersionParam,
          createdAtUtcMs: createdAtUtcMsParam,
          lastOpenedAtUtcMs: lastOpenedAtUtcMsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PuzzleProgressEntity] entity fields to define ObjectBox queries.
class PuzzleProgressEntity_ {
  /// See [PuzzleProgressEntity.id].
  static final id = obx.QueryIntegerProperty<PuzzleProgressEntity>(
    _entities[0].properties[0],
  );

  /// See [PuzzleProgressEntity.lichessPuzzleId].
  static final lichessPuzzleId = obx.QueryStringProperty<PuzzleProgressEntity>(
    _entities[0].properties[1],
  );

  /// See [PuzzleProgressEntity.solved].
  static final solved = obx.QueryBooleanProperty<PuzzleProgressEntity>(
    _entities[0].properties[2],
  );

  /// See [PuzzleProgressEntity.failed].
  static final failed = obx.QueryBooleanProperty<PuzzleProgressEntity>(
    _entities[0].properties[3],
  );

  /// See [PuzzleProgressEntity.attempts].
  static final attempts = obx.QueryIntegerProperty<PuzzleProgressEntity>(
    _entities[0].properties[4],
  );

  /// See [PuzzleProgressEntity.solvedCount].
  static final solvedCount = obx.QueryIntegerProperty<PuzzleProgressEntity>(
    _entities[0].properties[5],
  );

  /// See [PuzzleProgressEntity.failedCount].
  static final failedCount = obx.QueryIntegerProperty<PuzzleProgressEntity>(
    _entities[0].properties[6],
  );

  /// See [PuzzleProgressEntity.bestTimeMs].
  static final bestTimeMs = obx.QueryIntegerProperty<PuzzleProgressEntity>(
    _entities[0].properties[7],
  );

  /// See [PuzzleProgressEntity.firstSolvedAtMs].
  static final firstSolvedAtMs = obx.QueryIntegerProperty<PuzzleProgressEntity>(
    _entities[0].properties[8],
  );

  /// See [PuzzleProgressEntity.lastPlayedAtMs].
  static final lastPlayedAtMs = obx.QueryIntegerProperty<PuzzleProgressEntity>(
    _entities[0].properties[9],
  );
}

/// [PuzzleRunEntity] entity fields to define ObjectBox queries.
class PuzzleRunEntity_ {
  /// See [PuzzleRunEntity.id].
  static final id = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[0],
  );

  /// See [PuzzleRunEntity.catalogId].
  static final catalogId = obx.QueryStringProperty<PuzzleRunEntity>(
    _entities[1].properties[1],
  );

  /// See [PuzzleRunEntity.mode].
  static final mode = obx.QueryStringProperty<PuzzleRunEntity>(
    _entities[1].properties[2],
  );

  /// See [PuzzleRunEntity.startedAtMs].
  static final startedAtMs = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[3],
  );

  /// See [PuzzleRunEntity.endedAtMs].
  static final endedAtMs = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[4],
  );

  /// See [PuzzleRunEntity.score].
  static final score = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[5],
  );

  /// See [PuzzleRunEntity.streak].
  static final streak = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[6],
  );

  /// See [PuzzleRunEntity.mistakes].
  static final mistakes = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[7],
  );

  /// See [PuzzleRunEntity.minRating].
  static final minRating = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[8],
  );

  /// See [PuzzleRunEntity.maxRating].
  static final maxRating = obx.QueryIntegerProperty<PuzzleRunEntity>(
    _entities[1].properties[9],
  );

  /// See [PuzzleRunEntity.randomMode].
  static final randomMode = obx.QueryBooleanProperty<PuzzleRunEntity>(
    _entities[1].properties[10],
  );
}

/// [PuzzleSettingsEntity] entity fields to define ObjectBox queries.
class PuzzleSettingsEntity_ {
  /// See [PuzzleSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<PuzzleSettingsEntity>(
    _entities[2].properties[0],
  );

  /// See [PuzzleSettingsEntity.minRating].
  static final minRating = obx.QueryIntegerProperty<PuzzleSettingsEntity>(
    _entities[2].properties[1],
  );

  /// See [PuzzleSettingsEntity.maxRating].
  static final maxRating = obx.QueryIntegerProperty<PuzzleSettingsEntity>(
    _entities[2].properties[2],
  );

  /// See [PuzzleSettingsEntity.randomMode].
  static final randomMode = obx.QueryBooleanProperty<PuzzleSettingsEntity>(
    _entities[2].properties[3],
  );

  /// See [PuzzleSettingsEntity.selectedMode].
  static final selectedMode = obx.QueryStringProperty<PuzzleSettingsEntity>(
    _entities[2].properties[4],
  );
}

/// [UserStoreMetaEntity] entity fields to define ObjectBox queries.
class UserStoreMetaEntity_ {
  /// See [UserStoreMetaEntity.id].
  static final id = obx.QueryIntegerProperty<UserStoreMetaEntity>(
    _entities[3].properties[0],
  );

  /// See [UserStoreMetaEntity.schemaVersion].
  static final schemaVersion = obx.QueryIntegerProperty<UserStoreMetaEntity>(
    _entities[3].properties[1],
  );

  /// See [UserStoreMetaEntity.createdAtUtcMs].
  static final createdAtUtcMs = obx.QueryIntegerProperty<UserStoreMetaEntity>(
    _entities[3].properties[2],
  );

  /// See [UserStoreMetaEntity.lastOpenedAtUtcMs].
  static final lastOpenedAtUtcMs =
      obx.QueryIntegerProperty<UserStoreMetaEntity>(_entities[3].properties[3]);
}
