$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot

function Invoke-InDirectory {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][scriptblock]$Command
    )

    Push-Location $Path
    try {
        & $Command
    }
    finally {
        Pop-Location
    }
}

Write-Host "1/7 bpuzzles_format dependencies"
Invoke-InDirectory "packages\bpuzzles_format" {
    dart pub get
}

Write-Host "2/7 PuzzleCatalogStore ObjectBox code generation"
Invoke-InDirectory "packages\puzzle_catalog_store" {
    dart pub get
    dart run build_runner build --delete-conflicting-outputs
}

Write-Host "3/7 UserStore ObjectBox code generation"
Invoke-InDirectory "packages\user_store" {
    dart pub get
    dart run build_runner build --delete-conflicting-outputs
}

$modelPath = Join-Path $ProjectRoot `
    "packages\puzzle_catalog_store\lib\objectbox-model.json"
$fingerprintPath = Join-Path $ProjectRoot `
    "packages\puzzle_catalog_store\lib\src\catalog_model_fingerprint.g.dart"

if (-not (Test-Path $modelPath)) {
    throw "ObjectBox model was not generated: $modelPath"
}

$hash = (Get-FileHash $modelPath -Algorithm SHA256).Hash.ToLowerInvariant()
$content = @"
/// Generated by tool/setup_database_patch.ps1.
/// SHA-256 of packages/puzzle_catalog_store/lib/objectbox-model.json.
const String catalogModelFingerprint = '$hash';
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($fingerprintPath, $content, $utf8NoBom)

Write-Host "4/7 PC builder dependencies"
Invoke-InDirectory "tools\puzzle_catalog_builder" {
    dart pub get
}

Write-Host "5/7 ObjectBox native library for the PC builder"
& (Join-Path $PSScriptRoot "install_objectbox_native.ps1")

Write-Host "6/7 Flutter dependencies"
flutter pub get

Write-Host "7/7 Formatting"
dart format `
    "packages\bpuzzles_format" `
    "packages\puzzle_catalog_store" `
    "packages\user_store" `
    "tools\puzzle_catalog_builder" `
    "lib\data"

Write-Host ""
Write-Host "Database patch prepared."
Write-Host "Catalog model fingerprint: $hash"
Write-Host ""
Write-Host "Recommended checks:"
Write-Host "  flutter analyze"
Write-Host "  cd packages\bpuzzles_format; dart test"
Write-Host "  cd tools\puzzle_catalog_builder; dart test"
