/// Generated by tool/setup_database_patch.ps1.
/// SHA-256 of packages/puzzle_catalog_store/lib/objectbox-model.json.
const String catalogModelFingerprint =
    '350f0a9d8ce71eacef7312b808b104b5aabcd0f360bb525bc3b4e2e892dd1c48';
